# Uncomment this line to define a global platform for your project
platform :ios, '8.0'

target 'interview-app-swift' do
    pod "SwiftyJSON"
    pod "OAuthConsumer"
    pod 'SDWebImage', '~>3.6'
    pod 'OAuthSwift', '~>0.3.6'
end

target 'interview-app-swiftTests' do

end

